config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :people

  get '/facebook', to: 'dashboard#facebook'
  get '/facebook/:nombre', to: 'dashboard#facebook'

  get '/nickname', to: 'dashboard#nickname'
  get '/nickname/:nickname', to: 'dashboard#nickname'

  match 'add_people', to: 'dashboard#add_people', via: [:post]
  match 'search_people', to: 'people#search_people', via: [:post]
  
  match 'search_facebook_detail', to: 'people#search_facebook_detail', via: [:post]
  
  devise_scope :user do
    unauthenticated :user do
      root 'devise/sessions#new'
    end
    
    authenticated :user do
      root 'dashboard#index'
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @person = Person.new
    @people = Person.order(:id => :DESC)
  end

  def facebook
    @people = Person.all.limit(5)
    @detail = Detail.new

    if params[:social]
      nombre = params[:social][:nombre].tr(' ', '-')
      @social_people = get_list_facebook(nombre)
    end
  end

  def nickname
    @people = Person.all.limit(5)
    @detail = Detail.new

    if params[:social]
      nombre = params[:social][:nickname].tr(' ', '-')
      @social_people = get_list_social(nombre)
    end
  end
  
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def validate_usr(username)
    username.gsub!("https://www.facebook.com/", "")
    !!username[/^([A-Za-z0-9_](?:(?:[A-Za-z0-9_]|(?:\.(?!\.))){0,28}(?:[A-Za-z0-9_]))?)$/]
  end

  def get_username(username)
    username.gsub!("https://www.facebook.com/", "")
    username
  end
end

app/views/dashboard/facebook.html.erb
<div class="page-title">
  <div class="title_left">
    <h3>Búsqueda <small>por redes sociales</small></h3>
  </div>
</div>

<%= form_tag({controller: "dashboard", action: "facebook"}, method: "get", class: "form-horizontal form-label-left") do |f| %>

  <div class="form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Nombre y Apellidos <span class="required">*</span>
    </label>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= text_field(:social, :nombre, class: "form-control col-md-7 col-xs-12", value: (params[:social][:nombre] if params[:social])) %>
    </div>
  </div>
  
  <div class="form-group">
    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
      <%= submit_tag("Buscar", class: "btn btn-success") %>
    </div>
  </div>

  <div class="ln_solid"></div>
<% end %>

<div class="clearfix"></div>


<div class="col-md-12 col-sm-12 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <div class="col-xs-12 col-sm-6 emphasis">
        <h2>Resultados <small>de búsqueda</small></h2>
      </div>
      <div class="col-xs-12 col-sm-6 emphasis text-right">
        <button id="ShowModalAsignar" type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-lg">Asignar</button>
      </div>
      <div class="clearfix"></div>
    </div>

    <div class="x_content">
      <div id="social-table" class="table-responsive">
        <table class="table table-striped jambo_table bulk_action">
          <thead>
            <tr class="headings">
              <th>
                <input type="checkbox" id="check-all" class="flat">
              </th>
              <th class="column-title">Foto </th>
              <th class="column-title">Origen </th>
              <th class="column-title">Nombres y Apellidos </th>
              <th class="column-title"> </th>
              </th>
              <th class="bulk-actions" colspan="7">
                  ( <span class="action-cnt"> </span> )
              </th>
            </tr>
          </thead>

          <tbody>
            <% if @social_people %>
            <% @social_people.each do |person| %>
                <tr class="even pointer">
                  <td class="a-center ">
                    <input type="checkbox" class="flat" name="table_records">
                  </td>
                  <td class=" "><%= image_tag person[:img], style: "height: 7em;"  %> </td>
                  <td class=" ">Facebook </td>
                  <td class=" last">
                    <%= link_to person[:name], person[:link] %>
                  </td>
                  <td class="form_detail">
                    <%= form_tag search_facebook_detail_path, remote: :true do %>
                      <%= hidden_field_tag(:link, person[:link]) %>
                      <%= button_tag type: "submit", class: "btn btn-default", data: {toggle: "modal", target: ".bs-example-modal-sm"} do %>
                        <i class='fa fa-eye'></i> Ver detalles
                      <% end %>

                      <% if validate_usr(person[:link]) %>
                        <%= link_to nickname_path(social: {nickname: person[:link]} ), class: "btn btn-default" do %>
                          <i class='fa fa-sitemap'></i> Relacionados
                        <% end %>
                      <% end %>
                    <% end %>
                  </td>
                </tr>
            <% end %>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">
          Asociación de personas 
          <%= button_to search_people_path, remote: true, class: "btn btn-primary", data: {nombre: "", apodo: ""} do %>
            <i class='fa fa-refresh'></i>
          <% end %>
        </h4>
      </div>
      <div class="modal-body">
        <div>
          
          <%= form_tag(search_people_path, method: "post", remote: true, class: "x_title form-horizontal form-label-left input_mask") do %>
            <div class="col-md-4 col-sm-4 col-xs-12 form-group has-feedback">
              <%= text_field_tag(:nombre, "", class: "form-control has-feedback-left", placeholder: "Nombre") %>
              <span class="fa fa-user form-control-feedback left" aria-hidden="true"></span>
            </div>

            <div class="col-md-4 col-sm-4 col-xs-12 form-group has-feedback">
              <%= text_field_tag(:apodo, "", class: "form-control has-feedback-left", placeholder: "Apodo") %>
              <span class="fa fa-user form-control-feedback left" aria-hidden="true"></span>
            </div>

            <div class="col-md-4 col-sm-4 col-xs-12 form-group has-feedback">
              <button type="submit" class="btn btn-success" style="width: 100%">Buscar</button>
            </div>
          <% end %>

          <div class="x-panel">
            <%= render partial: "people/table_people_search", locals: {people: @people} %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
        <button type="button" class="btn btn-primary">Guardar</button>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
</div>

<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel2">Detalle de persona</h4>
      </div>
      <div id="content_detail_search" class="modal-body">
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
      </div>

    </div>
  </div>
</div>

<script type="text/javascript">
  // $(document).on("turbolinks:load", function() {
		$('#ShowModalAsignar').hide();
    
    $("#ShowModalAsignar").on("click", function()
    {
      let all_selected = $("#social-table tr.selected a");
      console.log(all_selected);
    })
    
  // });
</script>   

app/views/dashboard/index.html.erb
<%= render template: "people/new" %>

<div class="col-md-12 col-sm-12 col-xs-12">
  <div class="x_panel">

      <table class="table table-striped">
        <thead>
          <tr>
            <th>Nombre y apellidos</th>
            <th>Apodo</th>
            <th>Agregado el</th>
          </tr>
        </thead>
        <tbody>
          <% @people.each do |person| %>
            <tr>
              <td><%= person.nombre %></td>
              <td><%= person.apodo %></td>
              <td><%= person.created_at.strftime("%d %B, %Y") %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>

app/views/dashboard/nickname.html.erb
<div class="page-title">
  <div class="title_left">
    <h3>Búsqueda <small>por redes sociales</small></h3>
  </div>
</div>

<%= form_tag({controller: "dashboard", action: "nickname"}, method: "get", class: "form-horizontal form-label-left") do |f| %>

  <div class="form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Nickname <span class="required">*</span>
    </label>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= text_field(:social, :nickname, class: "form-control col-md-7 col-xs-12", value: (params[:social][:nickname] if params[:social])) %>
    </div>
  </div>
  
  <div class="form-group">
    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
      <%= submit_tag("Buscar", class: "btn btn-success") %>
    </div>
  </div>

  <div class="ln_solid"></div>
<% end %>

<div class="clearfix"></div>


<div class="col-md-12 col-sm-12 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <div class="col-xs-12 col-sm-6 emphasis">
        <h2>Resultados <small>de búsqueda</small></h2>
      </div>
      <div class="col-xs-12 col-sm-6 emphasis text-right">
        <button id="ShowModalAsignar" type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-lg">Asignar</button>
      </div>
      <div class="clearfix"></div>
    </div>

    <div class="x_content">
      <div id="social-table" class="table-responsive">
        <table class="table table-striped jambo_table bulk_action">
          <thead>
            <tr class="headings">
              <th>
                <input type="checkbox" id="check-all" class="flat">
              </th>
              <th class="column-title">Foto </th>
              <th class="column-title">Origen </th>
              <th class="column-title">Nombres y Apellidos </th>
              <th class="column-title"> </th>
              </th>
              <th class="bulk-actions" colspan="7">
                  ( <span class="action-cnt"> </span> )
              </th>
            </tr>
          </thead>

          <tbody>
            <% if @social_people %>
            <% @social_people.each do |person| %>
                <% if !person.empty? %>
                <tr class="even pointer">
                  <td class="a-center ">
                    <input type="checkbox" class="flat" name="table_records">
                  </td>
                  <td class=" "><%= image_tag person[:img], style: "height: 7em;"  %> </td>
                  <td class=" "><%= person[:origen] %> </td>
                  <td class=" last">
                    <%= link_to person[:name], person[:link] %>
                  </td>
                </tr>
                <% end %>
            <% end %>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">
          Asociación de personas 
          <%= button_to search_people_path, remote: true, class: "btn btn-primary", data: {nombre: "", apodo: ""} do %>
            <i class='fa fa-refresh'></i>
          <% end %>
        </h4>
      </div>
      <div class="modal-body">
        <div>
          
          <%= form_tag(search_people_path, method: "post", remote: true, class: "x_title form-horizontal form-label-left input_mask") do %>
            <div class="col-md-4 col-sm-4 col-xs-12 form-group has-feedback">
              <%= text_field_tag(:nombre, "", class: "form-control has-feedback-left", placeholder: "Nombre") %>
              <span class="fa fa-user form-control-feedback left" aria-hidden="true"></span>
            </div>

            <div class="col-md-4 col-sm-4 col-xs-12 form-group has-feedback">
              <%= text_field_tag(:apodo, "", class: "form-control has-feedback-left", placeholder: "Apodo") %>
              <span class="fa fa-user form-control-feedback left" aria-hidden="true"></span>
            </div>

            <div class="col-md-4 col-sm-4 col-xs-12 form-group has-feedback">
              <button type="submit" class="btn btn-success" style="width: 100%">Buscar</button>
            </div>
          <% end %>

          <div class="x-panel">
            <%= render partial: "people/table_people_search", locals: {people: @people} %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
        <button type="button" class="btn btn-primary">Guardar</button>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
</div>

<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel2">Detalle de persona</h4>
      </div>
      <div id="content_detail_search" class="modal-body">
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
      </div>

    </div>
  </div>
</div>

<script type="text/javascript">
  // $(document).on("turbolinks:load", function() {
		$('#ShowModalAsignar').hide();
    
    $("#ShowModalAsignar").on("click", function()
    {
      let all_selected = $("#social-table tr.selected a");
      console.log(all_selected);
    })
    
  // });
</script>   