config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :people

  get '/facebook', to: 'dashboard#facebook'
  get '/facebook/:nombre', to: 'dashboard#facebook'

  get '/nickname', to: 'dashboard#nickname'
  get '/nickname/:nickname', to: 'dashboard#nickname'

  match 'add_people', to: 'dashboard#add_people', via: [:post]
  match 'search_people', to: 'people#search_people', via: [:post]
  
  match 'search_facebook_detail', to: 'people#search_facebook_detail', via: [:post]
  
  devise_scope :user do
    unauthenticated :user do
      root 'devise/sessions#new'
    end
    
    authenticated :user do
      root 'dashboard#index'
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Osint</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <% unless notice.nil? %>
    <div class="notice alert alert-success alert-dismissible fade in" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
      </button>
      <%= notice %>
    </div>
  <% end %>
  <% unless alert.nil? %>
    <div class="alert alert-danger alert-dismissible fade in" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
      </button>
      <%= alert %>
    </div>
  <% end %>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="<%= root_path %>" class="site_title"><span>O.S.I.N.T</span></a>
            </div>

            <div class="clearfix"></div>

            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <h3>Principal</h3>
                <ul class="nav side-menu">
                  <li><a href="<%= root_path %>"><i class="fa fa-home"></i> Registro persona <span class="fa fa-chevron-right"></span></a></li>
                  <li><a><i class="fa fa-bar-chart-o"></i> Búsqueda Persona <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="<%= facebook_path %>">Facebook name</a></li>
                      <li><a href="<%= nickname_path %>">Nickname</a></li>
                    </ul>
                  </li>
                  <li><a href="https://taringa.net"><i class="fa fa-bar-chart-o"></i> Búsqueda en Entidad <span class="fa fa-chevron-right"></span></a></li>
                  <li><a href="https://taringa.net"><i class="fa fa-table"></i> Reportes <span class="fa fa-chevron-right"></span></a></li>
                </ul>
              </div>
            </div>
            <!-- /sidebar menu -->

            <!-- /menu footer buttons -->
            <div class="sidebar-footer hidden-small">
              <a data-toggle="tooltip" data-placement="top" title="Settings">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Lock">
                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
              </a>
            </div>
            <!-- /menu footer buttons -->
          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>

              <ul class="nav navbar-nav navbar-right">
                <li class="">
                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <%= current_user.username %>
                    <span class=" fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-usermenu pull-right">
                    <li>
                      <%= link_to "Cerrar sesión", destroy_user_session_path, :method => :delete %>
                    </li>
                  </ul>
                </li>

              </ul>
            </nav>
          </div>
        </div>
        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" role="main">
          <div class="">
            
            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <%= yield %>
              </div>
            </div>
          </div>
        </div>
        <!-- /page content -->

        <!-- footer content -->
        <footer>
          <div class="pull-right">
            Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
    </div>

  </body>
</html>

app/views/layouts/unauthenticated.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Osint</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body class="login">
    <% unless notice.nil? %>
      <div class="notice alert alert-success alert-dismissible fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
        </button>
        <%= notice %>
      </div>
    <% end %>
    <% unless alert.nil? %>
      <div class="alert alert-danger alert-dismissible fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
        </button>
        <%= alert %>
      </div>
    <% end %>
    <div>
      <a class="hiddenanchor" id="signup"></a>
      <a class="hiddenanchor" id="signin"></a>

      <div class="login_wrapper">
        <%= yield %>
      </div>
    </div>
  </body>
  
</html>